import os
from typing import Iterator

from sayou.core.registry import register_component
from sayou.core.schemas import SayouTask

from ..interfaces.base_generator import BaseGenerator


@register_component("generator")
class GoogleCalendarGenerator(BaseGenerator):
    """
    Generates tasks using OAuth 2.0 Token.
    Requires 'sayou_google_token.json' (generated by auth script).
    """

    component_name = "GoogleCalendarGenerator"
    SUPPORTED_TYPES = ["google_calendar"]

    @classmethod
    def can_handle(cls, uri: str) -> float:
        return 1.0 if uri.startswith("gcal://") else 0.0

    def _do_generate(self, source: str, **kwargs) -> Iterator[SayouTask]:
        token_path = kwargs.get("google_token_path")

        if not os.path.exists(token_path):
            raise FileNotFoundError(
                f"Google Token not found at {token_path}. Run authentication script first."
            )

        calendar_id = source.replace("gcal://", "") or "primary"

        yield SayouTask(
            uri=source,
            source_type="google_calendar",
            params={
                "calendar_id": calendar_id,
                "token_path": token_path,
            },
            meta={
                "source": "google_calendar",
                "calendar_id": calendar_id,
                "filename": f"calendar_{calendar_id.replace('@', '_')}",
            },
        )
